In [1]:
import numpy as np
from sympy import Matrix

In [2]:
# Find determinant:
#M = Matrix([[7, 4, 1], [3, 0, 1], [-4, 4, 0]])
#M = Matrix(Md)
A = np.array([[7, 4, 1], [3, 0, 1], [-4, 4, 0]])
#A = [[5.,3.,1.],[3.,9.,4.],[1.,3.,5.]]
B = [[9.0],[16.0],[9.0]]

detA = Matrix(A).det()
print("The detA =",detA,"\n")
if Matrix(A).det() != 0:
    print("Because the determinant of A is not zero, A is invertible and the system has a unique solution;"+"\n"+" Thus Cramer's rule and be applied")

The detA = -32 

Because the determinant of A is not zero, A is invertible and the system has a unique solution;
 Thus Cramer's rule and be applied


In [3]:
#variable x1 can be found by A1(b), where A1(b) is obtained from A w/ replacing column 1 by the vector b:
newA = np.array(list(A.T)[1:]).T
A1_b=(np.column_stack((B,newA)))
print("A1(b):"+"\n",A1_b)
detA1_b = Matrix(A1_b).det()
print("detA1(b) =",detA1_b)
print("x1 =",detA1_b/detA)

#variable x2 can be found by A2(b), where A2(b) is obtained from A w/ replacing column 2 by the vector b:
newA21 = list(A.T)[0]
#newA22 = list(B.T)
newA23 = list(A.T)[2]
newA2 = A1_b=(np.column_stack((newA21,B,newA23)))
print("\n"+"A2(b):"+"\n", newA2)
detA2_b = Matrix(newA2).det()
print("detA2(b) =",detA2_b)
print("x2 =",detA2_b/detA)

#variable x3 can be found by A3(b), where A3(b) is obtained from A w/ replacing column 3 by the vector b:
newA3 = np.array(list(A.T)[0:2]).T
A3_b=(np.column_stack((newA3,B)))
print("\n"+"A3(b):"+"\n",A3_b)
detA3_b = Matrix(A3_b).det()
print("detA3(b) =",detA3_b)

print("x3 =",detA3_b/detA)

A1(b):
 [[ 9.  4.  1.]
 [16.  0.  1.]
 [ 9.  4.  0.]]
detA1(b) = 64.0000000000000
x1 = -2.00000000000000

A2(b):
 [[ 7.  9.  1.]
 [ 3. 16.  1.]
 [-4.  9.  0.]]
detA2(b) = -8.00000000000000
x2 = 0.250000000000000

A3(b):
 [[ 7.  4.  9.]
 [ 3.  0. 16.]
 [-4.  4.  9.]]
detA3(b) = -704.000000000000
x3 = 22.0000000000000


In [4]:
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))
d = float(input("Enter d: "))
e = float(input("Enter e: "))
f = float(input("Enter f: "))

##a*x + by = e
##cx + dy = f

if (a*d - b*c == 0):
    print("The equation has no solution")
else:
    x = (e*d-b*f)/(a*d-b*c)
    y = (a*f-e*d)/(a*d-b*c)

    print ("x=%s" % x, "y=%s" % y)

Enter a: 


ValueError: could not convert string to float: ''