## Diagonalization
A square matrix M is diagonalizable if it is similar to a diagonal matrix. In other words, M is diagonalizable if there exists an invertible matrix P such that D=P−1MP is a diagonal matrix.
A beautiful result in linear algebra is that a square matrix M of size n is diagonalizable if and only if M has n independent eigevectors. Furthermore, M=PDP−1 where the columns of P are the eigenvectors of M and D has corresponding eigenvalues along the diagonal.
Let's use this to construct a matrix with given eigenvalues λ1=3,λ2=1, and eigenvectors v1=[1,1]T,v2=[1,−1]T.

In [8]:
import numpy as np
from sympy import Matrix
from pprint import pprint
from scipy import linalg

In [2]:
P = np.array([[2,1],[1,-1]])
print(P)

[[ 2  1]
 [ 1 -1]]


In [3]:
D = np.diag((3,1))
print(D)

[[3 0]
 [0 1]]


In [4]:
## SET-UP THE MATRIX A
A2 = np.array([[5, 0, 0, 0], 
              [0, 5, 0, 0], 
              [1, 4, -3, 0], 
              [-1, -2, 0, -3]]) 

A4 = np.array([[2, 0, 0],
              [-1, 1, 0],
              [5, 3, -3]])

A5 = np.array([[2, 3],
              [4, 1]])

#A = Matrix([[0, 2], [1, -3]])
A = Matrix(A2)

print(A.eigenvects())
def is_whole(d):
    """Whether or not d is a whole number."""
    return isinstance(d, int) or (isinstance(d, float) and d.is_integer())

[(-3, 2, [Matrix([
[0],
[0],
[1],
[0]]), Matrix([
[0],
[0],
[0],
[1]])]), (5, 2, [Matrix([
[-8],
[ 4],
[ 1],
[ 0]]), Matrix([
[-16],
[  4],
[  0],
[  1]])])]


In [5]:
import math
from math import gcd
from functools import reduce
from fractions import Fraction
from decimal import Decimal
def find_gcd(list):
    x = reduce(gcd, list)
    return x
matrix = []
for i in range(len(A.eigenvects())):
    print("Eigenvalue:", A.eigenvects()[i][0], "; Multiplicity:", A.eigenvects()[i][1])
    if len(A.eigenvects()[i][2]) > 1:
        mult = 1 
        eigenvect = A.eigenvects()[i][2]
        for x in range(len(eigenvect)):
            temp_eigenvect = eigenvect[x]
            for t in temp_eigenvect:
                if not is_whole(t):
                    mult=Fraction(str(t)).denominator
                    temp_eigenvect = temp_eigenvect*mult
            #matrix.append([ele for ele in temp_eigenvect])
            matrix.append([ele/find_gcd(list(temp_eigenvect)) for ele in temp_eigenvect])
            #matrix.append([ele/max(list(temp_eigenvect)) for ele in temp_eigenvect])
            #pprint(temp_eigenvect)
    #print(A.eigenvects()[i][-1])
    elif len(A.eigenvects()[i][2]) == 1: 
        mult = 1 
        eigenvect=A.eigenvects()[i][2]
        for x in range(len(eigenvect)):
            #pprint(A.eigenvects()[i][2][x])
            temp_eigenvect = eigenvect[x]
            for t in temp_eigenvect:
                #if not is_whole(t):
                if str(t).count('/') >0:
                    print(t)
                    if t!=0:
                        mult=np.reciprocal(Fraction(str(t)))#.denominator
                        div = Fraction(str(t)).numerator
                        #print(mult)
                        temp_eigenvect = temp_eigenvect*mult
                        print(temp_eigenvect)
                        break
                    #if div != 0:
                        #temp_eigenvectt=[]
                        #for ii in temp_eigenvect:
                            #temp_eigenvectt.append(float(ii))
                            #print(div)
                        #temp_eigenvectt = Matrix(np.array(temp_eigenvectt))  
                        #print(temp_eigenvectt)
                        #temp_eigenvect = temp_eigenvect
                    #pprint(temp_eigenvect)
            #matrix.append([ele for ele in temp_eigenvect])
            #matrix.append([ele/find_gcd(list(temp_eigenvect)) for ele in temp_eigenvect])
            #matrix.append([ele/max(list(temp_eigenvect)) for ele in temp_eigenvect])
            matrix.append(temp_eigenvect)
#if len(matrix[0]) != len(matrix):
    #print("WARNING: THIS MATRIX CANNOT BE DIAGONALIZED BC THERE ARENT ENOUGH N EIGENVECTORS FOR NxN MATRIX.")
else:
    print("\n",matrix)
    M = Matrix(np.array(matrix))
    # reversing column order in matrix   np.fliplr(arr)
    flipped_M =Matrix(np.fliplr(np.array(matrix).T))
    pprint(M.T) 
    print("\n","Reversed:", "\n",matrix[::-1])
    pprint(flipped_M)

Eigenvalue: -3 ; Multiplicity: 2
Eigenvalue: 5 ; Multiplicity: 2

 [[0, 0, 1, 0], [0, 0, 0, 1], [-8, 4, 1, 0], [-16, 4, 0, 1]]
Matrix([
[0, 0, -8, -16],
[0, 0,  4,   4],
[1, 0,  1,   0],
[0, 1,  0,   1]])

 Reversed: 
 [[-16, 4, 0, 1], [-8, 4, 1, 0], [0, 0, 0, 1], [0, 0, 1, 0]]
Matrix([
[-16, -8, 0, 0],
[  4,  4, 0, 0],
[  0,  1, 0, 1],
[  1,  0, 1, 0]])


***An n×n matrix is diagonalizable if and only if it has n linearly independent eigenvectors. For a diagonalizable matrix A=PDP−1, these eigenvectors are the columns of P and the corresponding eigenvalues are the diagonal entries of D. Remember to use integers or fractions for any entries in a matrix.***

## Matrix Powers
Let M be a square matrix. Computing powers of M by matrix multiplication
let's use diagonalization to compute M^k more efficiently
Let's compute M^k

In [6]:
#Matrix from above... construct a matrix with given eigenvalues... and eigenvectors v1=[1,1]T,v2=[1,−1]T.
#construct a matrix with given eigenvalues , and eigenvectors .
P = np.array([[1,1,0],[1,-1, 0], [0,0,1]])
print(P)

[[ 1  1  0]
 [ 1 -1  0]
 [ 0  0  1]]


In [10]:
Pinv = linalg.inv(P)
#Pinv = np.array([[-5,-3],[-3,-2]]) 
print(Pinv)

[[ 0.5  0.5 -0. ]
 [ 0.5 -0.5  0. ]
 [ 0.   0.   1. ]]


In [11]:
k = 2019

In [12]:
#diagonal from above... construct a matrix with given eigenvalues λ1=3,λ2=1 and eigenvectors...
D = np.diag((1,1,-1))
print(D)

[[ 1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [13]:
##Using diagonalization to compute M to k power.
P @ D**k @ Pinv

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0., -1.]])

In [14]:
# Python function to find the factors of a number

# This function computes the factor of the argument passed
def print_factors(x):
   print("The factors of",x,"are:")
   for i in range(1, x + 1):
       if x % i == 0:
           print(i)

num = 509
num2 = 256

print(print_factors(num), print_factors(num2))

The factors of 509 are:
1
509
The factors of 256 are:
1
2
4
8
16
32
64
128
256
None None
