## Compute eigenvalues and eigenvectors of a square matrix
The function scipy.linalg.eig computes eigenvalues and eigenvectors of a square matrix .

***Definition***
Let A be a square matrix. 
A non-zero vector v is an eigenvector for A with eigenvalue λ if
Av=λv .
Rearranging the equation, we see that v is a solution of the homogeneous system of equations
(A−λI)v=0 .
where I is the identity matrix of size n. Non-trivial solutions exist only if the matrix A−λI is singular which means det(A−λI)=0. Therefore eigenvalues of A are roots of the characteristic polynomial
p(λ)=det(A−λI)

In [5]:
import numpy as np
from scipy import linalg

In [3]:
A = np.array([[1,0],[0,-2]])
print(A)

[[ 1  0]
 [ 0 -2]]


***The function la.eig returns a tuple (eigvals,eigvecs) where eigvals is a 1D NumPy array of complex numbers giving the eigenvalues of A, and eigvecs is a 2D NumPy array with the corresponding eigenvectors in the columns:***

In [6]:
results = linalg.eig(A)

In [7]:
#The eigenvalues of A are:
print(results[0])

[ 1.+0.j -2.+0.j]


In [8]:
#The corresponding eigenvectors are:
print(results[1])

[[1. 0.]
 [0. 1.]]


In [14]:
#Unpack the tuple:
eigvals, eigvecs = linalg.eig(A)
print("eigenvalues:", "\n", eigvals,"\n")
print("eigenvectors:", "\n", eigvecs)

eigenvalues: 
 [ 1.+0.j -2.+0.j] 

eigenvectors: 
 [[1. 0.]
 [0. 1.]]


In [15]:
#If we know that the eigenvalues are real numbers (ie. if  is symmetric), 
#then we can use the NumPy array method .real to convert the array of eigenvalues to real numbers:
eigvals = eigvals.real
print(eigvals)

[ 1. -2.]


In [16]:
#The position of an eigenvalue in the array eigvals correspond to the column in eigvecs with its eigenvector:
lambda1 = eigvals[1]
print(lambda1)

-2.0


In [17]:
v1 = eigvecs[:,1].reshape(2,1)
print(v1)

[[0.]
 [1.]]


In [18]:
A @ v1

array([[ 0.],
       [-2.]])

In [19]:
lambda1 * v1

array([[-0.],
       [-2.]])