## IS THE MATRIX INVERTIBLE?

Use the Invertible Matrix Theorem to determine if the matrix is invertible. Let A be a square n×n matrix. Then the following statements are equivalent. That is, for a given A, the statements are either all true or all false.

a. 	A is an invertible matrix.

b. 	A is row equivalent to the n×n identity matrix.

c. 	A has n pivot positions.

d. 	The equation Ax=0 has only the trivial solution.

e. 	The columns of A form a linearly independent set.

f. 	The linear transformation x ↦ Ax is one-to-one.

g. 	The equation Ax=b has at least one solution for each b in ℝn.

h. 	The columns of A span ℝn.

i. 	The linear transformation x ↦ Ax maps ℝn onto ℝn.

j. 	There is an n×n matrix C such that CA=I.

k. 	There is an n×n matrix D such that AD=I.

l.	AT is an invertible matrix.

In [1]:
import numpy as np
from sympy import Matrix

In [2]:
A = [[1,-2,-5],
     [0,4,3],
     [-4,5,0]]
A = np.array(A)
print("The Matrix has rank:"+"\n",np.linalg.matrix_rank(A))

# Row Reduce the Matrix:
M_rref = Matrix(A).rref()   
      
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))

The Matrix has rank:
 3
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


## Compute Determinant

If det A is non-zero, the matrix A is invertible. Since the matrix A is invertible, the columns of A are linearly independent, by the invertible matrix theorem.

In [3]:
#M = Matrix([[1, 0, 1], [2, -1, 3], [4, 3, 2]])
M = Matrix(A)
M.det()

-71

## FIND INVERSE OF MATRIX

The inverse of a matrix exists only if the matrix is non-singular i.e., determinant should not be 0. 
Using determinant and adjoint, we can easily find the inverse of a square matrix using below formula:

In [4]:
MM = Matrix(A)
if MM.det() != 0:
    print("det =",MM.det(),"\n","Inverse is: ","\n", np.linalg.inv(np.array(A)))
else:
    print("Inverse doesn't exist")  

det = -71 
 Inverse is:  
 [[ 0.21126761  0.35211268 -0.1971831 ]
 [ 0.16901408  0.28169014  0.04225352]
 [-0.22535211 -0.04225352 -0.05633803]]


In [5]:
# Taking a 4 * 4 matrix 
A = np.array([[6, 1, 1, 3], 
              [4, -2, 5, 1], 
              [2, 8, 7, 6], 
              [3, 1, 9, 7]]) 
  
# Calculating the inverse of the matrix 
print(np.linalg.inv(A))

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
