## MATRIX MULTIPLICATION
When doing multiplication:

-The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.

-And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.

-Multiplication is the dot product of rows and columns. Rows of the 1st matrix with columns of the 2nd

***w is in Nul(A) if Aw = [[0],[0]]***

In [1]:
import numpy as np

In [2]:
P = [[1, 1, 0], [1, -1, 0], [0, 0, -1]]
Q = [[0.5, 0.5, 0], [0.5, -0.5, 0], [0, 0, 1]]

P = np.array(P)
Q = np.array(Q)

In [3]:
#Check that the matrices can be multiplied:
p_shape = P.shape
q_shape = Q.shape
if p_shape[1] != q_shape[0]:
    print("Matrix P does not have the same number of columns as Matrix Q has rows -- Multiplication Fails Here!")
else:
    ## CAREFULE HERE AS THE THIRD ROW ISN'T ALWAYS PRINTED 
    PxQ = np.dot(P,Q)
    print(PxQ)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
