## Solve the Matrix Equation Ax=b for x:

In [1]:
import numpy as np

A = [[1,5,-5],
     [-2,-4,3],
     [5,3,5]]
b = [16,-21, 44]

In [2]:
#x = np.linalg.lstsq(A,b)
#print(x)

In [3]:
a = np.array(A)
b = np.array(b)
print(a, '\n\n', b)

[[ 1  5 -5]
 [-2 -4  3]
 [ 5  3  5]] 

 [ 16 -21  44]


***Solve for x using numpy.linalg***

In [4]:
x = np.linalg.tensorsolve(a, b)#x, axes=b)#.ndim)
print(x)

[6. 3. 1.]


***Solve for x using numpy and x equals b multiplied by the inverse matrix of A***

***IF Ax=b, x = (A^-1)b***

In [5]:
x = np.dot(np.linalg.inv(A),b)
print(x)

[6. 3. 1.]


***Solve for x using scipy.linalg***

In [6]:
from scipy.linalg import solve

x = solve(A,b)
print(x)

[6. 3. 1.]


***Now we can test to solve for b***

In [7]:
np.dot(A,x) 

array([ 16., -21.,  44.])