## Solve system of Linear Equations

either use linalg.inv() and linalg.dot() methods in chain to solve a system of linear equations, or simply use the solve() method. The solve() method is preferred.

To find the value of x and y variables in Equation 1, we need to find the values in the matrix X. To do so, we can take the dot product of the inverse of matrix A, and the matrix B as shown below:

In [4]:
from sympy import Matrix
import numpy as np

In [5]:
#4x  + 3y = 20
#-5x + 9y = 26

#A = [[ 4   3]
     #[-5   9]]
#A = np.array([[4, 3], [-5, 9]])
A = np.array([[7, 4, 1], [3, 0, 1], [-4, 4, 0]])
#A = np.array([[1, 2, 0, -3], [3, 6, 0, -9]])
#A = np.array([[1, -2, -1, 3], [-2, 4, 5, -5], [3, -6, -6, 8]])
#A = np.array([[1, 0, 5, -5, 2, -7], [0, 0, 1, 0, 0,-2], [0, 0, 0, 0, 1, 3], [0, 0, 0, 0, 0, 0]])
print("Matrix A:"+"\n",A)

#X = [[x]
     #[y]]

#B = [[20]
     #[26]]
#B = np.array([20, 26])
#B = np.array([25, -10, -4])
#B = np.array([0, 0])
B = np.array([8, 2, 4])
#B = np.array([0, 0, 0, 0])

try:
    inv_A = np.linalg.inv(A)
    # METHOD 1: 
    X = np.linalg.inv(A).dot(B)
    # METHOD 2: 
    X2 = np.linalg.solve(A,B)
    
    free_vars = []
    #A_new = np.hstack((A,B))
    numcols = A.shape[1]
    A_new=(np.column_stack((A,B)))
    print("Augmented Matrix [A B]"+"\n",A_new)
    M_rref = Matrix(A_new).rref()     
    print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref)) 
    for i in range(0,numcols):
        if i not in list(M_rref[1]):
            free_vars.append(i)
    print("\n"+"the free variables are:")
    for ii in free_vars:
        print("X"+str(ii+1))
    for iii in range(0,numcols):
        if iii in list(M_rref[1]):
            print("Write X"+str(iii+1)+" in terms of the free variables")
    print("\n"+"Then write solution X in vector form [X1, X2, X3...Xn] = ... in terms of free variables")
    col_range = (M_rref[0]).shape[1]-1 
    for l in np.array(M_rref[0]):
        l = list(l)
        if l[:col_range].count(0) == len(l[:col_range]):
            if l[-2] == 0 and l[-1] != 0:
                print("NO SOLUTION DUE TO ROW:"+"\n"+l)
                    
    if str(X) != str(X2):# or X[1]!=X2[1]:
        print("UH OH! A discrepancy has occured between answers")
   
    else: 

        print("Method1 answer:",X,"\n\n","Method2 answer:",X2)
except Exception as e:
    print(e,"\n", "Unable to solve non-square matrix; must resolve w/ row-reduction"+"\n")
    free_vars = []
    #A_new = np.hstack((A,B))
    numcols = A.shape[1]
    A_new=(np.column_stack((A,B)))
    print("Augmented Matrix [A B]"+"\n",A_new)
    M_rref = Matrix(A_new).rref()     
    print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref)) 
    for i in range(0,numcols):
        if i not in list(M_rref[1]):
            free_vars.append(i)
    print("\n"+"the free variables are:")
    for ii in free_vars:
        print("X"+str(ii+1))
    for iii in range(0,numcols):
        if iii in list(M_rref[1]):
            print("Write X"+str(iii+1)+" in terms of the free variables")
    print("\n"+"Then write solution X in vector form [X1, X2, X3...Xn] = ... in terms of free variables")
    col_range = (M_rref[0]).shape[1]-1 
    for l in np.array(M_rref[0]):
        l = list(l)
        if l[:col_range].count(0) == len(l[:col_range]):
            if l[-2] == 0 and l[-1] != 0:
                print("\n"+"NO SOLUTION DUE TO ROW:"+"\n"+str(l))

Matrix A:
 [[ 7  4  1]
 [ 3  0  1]
 [-4  4  0]]
Augmented Matrix [A B]
 [[ 7  4  1  8]
 [ 3  0  1  2]
 [-4  4  0  4]]
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0, 1/4],
[0, 1, 0, 5/4],
[0, 0, 1, 5/4]]), (0, 1, 2))

the free variables are:
Write X1 in terms of the free variables
Write X2 in terms of the free variables
Write X3 in terms of the free variables

Then write solution X in vector form [X1, X2, X3...Xn] = ... in terms of free variables
Method1 answer: [0.25 1.25 1.25] 

 Method2 answer: [0.25 1.25 1.25]


In [6]:
#https://integratedmlai.com/system-of-equations-solution/
def print_matrix(Title, M):
    print(Title)
    for row in M:
        print([round(x,3)+0 for x in row])
        
def print_matrices(Action, Title1, M1, Title2, M2):
    print(Action)
    print(Title1, '\t'*int(len(M1)/2)+"\t"*len(M1), Title2)
    for i in range(len(M1)):
        row1 = ['{0:+7.3f}'.format(x) for x in M1[i]]
        row2 = ['{0:+7.3f}'.format(x) for x in M2[i]]
        print(row1,'\t', row2)
        
def zeros_matrix(rows, cols):
    A = []
    for i in range(rows):
        A.append([])
        for j in range(cols):
            A[-1].append(0.0)

    return A

def copy_matrix(M):
    rows = len(M)
    cols = len(M[0])

    MC = zeros_matrix(rows, cols)

    for i in range(rows):
        for j in range(cols):
            MC[i][j] = M[i][j]

    return MC

def matrix_multiply(A,B):
    rowsA = len(A)
    colsA = len(A[0])

    rowsB = len(B)
    colsB = len(B[0])

    if colsA != rowsB:
        print('Number of A columns must equal number of B rows.')
        sys.exit()

    C = zeros_matrix(rowsA, colsB)

    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += A[i][ii] * B[ii][j]
            C[i][j] = total

    return C

In [7]:
A = [[5.,3.,1.],[3.,9.,4.],[1.,3.,5.]]
B = [[9.0],[16.0],[9.0]]

In [8]:
AM = copy_matrix(A)
n = len(A)
BM = copy_matrix(B)

print_matrices('Starting Matrices are:', 'AM Matrix', AM, 
               'IM Matrix', BM)
print()

indices = list(range(n)) # allow flexible row referencing ***
for fd in range(n): # fd stands for focus diagonal
    fdScaler = 1.0 / AM[fd][fd]
    # FIRST: scale fd row with fd inverse. 
    for j in range(n): # Use j to indicate column looping.
        AM[fd][j] *= fdScaler
    BM[fd][0] *= fdScaler
    
    # Section to print out current actions:
    string1  = '\nUsing the matrices above, '
    string1 += 'Scale row-{} of AM and BM by '
    string2  = 'diagonal element {} of AM, '
    string2 += 'which is 1/{:+.3f}.\n'
    stringsum = string1 + string2
    val1 = fd+1; val2 = fd+1
    Action = stringsum.format(val1,val2,round(1./fdScaler,3))
    print_matrices(Action, 'AM Matrix', AM, 'BM Matrix', BM)
    print()
    
    # SECOND: operate on all rows except fd row.
    for i in indices[0:fd] + indices[fd+1:]: # *** skip fd row.
        crScaler = AM[i][fd] # cr stands for "current row".
        for j in range(n): # cr - crScaler*fdRow.
            AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
        BM[i][0] = BM[i][0] - crScaler * BM[fd][0]
        
        # Section to print out current actions:
        string1  = 'Using matrices above, subtract {:+.3f} *'
        string1 += 'row-{} of AM from row-{} of AM, and '
        string2 = 'subtract {:+.3f} * row-{} of BM '
        string2 += 'from row-{} of BM\n'
        val1 = i+1; val2 = fd+1
        stringsum = string1 + string2
        Action = stringsum.format(crScaler, val2, val1, 
                                  crScaler, val2, val1)
        print_matrices(Action, 'AM Matrix', AM, 
                               'BM Matrix', BM)
        print()

Starting Matrices are:
AM Matrix 				 IM Matrix
[' +5.000', ' +3.000', ' +1.000'] 	 [' +9.000']
[' +3.000', ' +9.000', ' +4.000'] 	 ['+16.000']
[' +1.000', ' +3.000', ' +5.000'] 	 [' +9.000']


Using the matrices above, Scale row-1 of AM and BM by diagonal element 1 of AM, which is 1/+5.000.

AM Matrix 				 BM Matrix
[' +1.000', ' +0.600', ' +0.200'] 	 [' +1.800']
[' +3.000', ' +9.000', ' +4.000'] 	 ['+16.000']
[' +1.000', ' +3.000', ' +5.000'] 	 [' +9.000']

Using matrices above, subtract +3.000 *row-1 of AM from row-2 of AM, and subtract +3.000 * row-1 of BM from row-2 of BM

AM Matrix 				 BM Matrix
[' +1.000', ' +0.600', ' +0.200'] 	 [' +1.800']
[' +0.000', ' +7.200', ' +3.400'] 	 ['+10.600']
[' +1.000', ' +3.000', ' +5.000'] 	 [' +9.000']

Using matrices above, subtract +1.000 *row-1 of AM from row-3 of AM, and subtract +1.000 * row-1 of BM from row-3 of BM

AM Matrix 				 BM Matrix
[' +1.000', ' +0.600', ' +0.200'] 	 [' +1.800']
[' +0.000', ' +7.200', ' +3.400'] 	 ['+10.600']
[' 

In [9]:
print("Now we multiply the original A matrix times our solution for X, which is BM.")
print_matrix('If we get our starting X, our solution is proved.\n', matrix_multiply(A,BM))

Now we multiply the original A matrix times our solution for X, which is BM.
If we get our starting X, our solution is proved.

[9.0]
[16.0]
[9.0]
